### ISSUE TITLE
Script Detected

### ISSUE THREAD

**Issue by Sadykhzadeh** [GameHackerC/Krunker.io-Hack#6]
It happened... Again(
![image](https://user-images.githubusercontent.com/51178055/58745358-0f9aad00-8461-11e9-8a0f-a9d1b176e6db.png)

**Comment by GameHackerC** [comment]
i will fix it
dont worry

**Comment by GameHackerC** [comment]
i fixed it

**Comment by GameHackerC** [comment]
but u have to like the file

**Comment by GameHackerC** [comment]
and follow me
